import type { Lang } from '../i18n/langs';

/*
 * Textos que emede escribe dentro de los archivos generados (andamiaje de la memoria, índices, canario,
 * guardarraíles), en el idioma del contenido. Variables: {nombre}.
 * El resto del contenido (memoria, prompts, skills) lo escribe el usuario o la IA en ese mismo idioma.
 */

const es = {
  rules: 'Reglas',
  appliesTo: 'Aplica a',
  agents: 'Subagentes disponibles',
  skills: 'Skills disponibles',
  delegate: 'Delegá esta tarea al subagente `{a}`.',
  useSkills: 'Usá la(s) skill(s): {s}.',
  args: 'los argumentos que el usuario indique',
  overview: 'Resumen',
  stack: 'Stack',
  cmds: 'Comandos esenciales',
  structure: 'Estructura',
  conventions: 'Convenciones',
  mcp: 'Tenés disponible el/los servidor(es) MCP: {m}.',
  cmdSkill: 'Flujo /{n}. Usar solo cuando el usuario lo pida explícitamente. {d}',
  envExample: 'Variables de entorno que usan los servidores MCP. Definilas en tu entorno; no subas los valores al repo.',
  plan: '## Plan del proyecto\n\nEl plan completo está en `docs/PLAN.md`. Leelo antes de empezar una fase o tarea y respetá su orden y sus criterios de aceptación.',
  canaryTitle: 'Canario de contexto',
  canaryName: 'Dirigite siempre a mí como **{phrase}**: empezá **cada** respuesta con “{phrase},”. Es una verificación: si dejás de llamarme así, significa que perdiste estas instrucciones y hay que volver a cargarlas.',
  canaryMarker: 'Empezá **cada** respuesta con `{phrase}` en la primera línea. Es una verificación: si la marca falta, significa que perdiste estas instrucciones y hay que volver a cargarlas.',
  canaryRule1: 'No inventes archivos, funciones, APIs, comandos, flags ni versiones: verificalos leyendo el código o la documentación antes de usarlos.',
  canaryRule2: 'Si no estás seguro de algo, decilo y explicá cómo verificarlo en lugar de suponer.',
  canaryRule3: 'Cuando afirmes algo sobre el código, citá la ruta (y la línea si aplica).',
  agentCanaryName: 'Empezá tu informe final con “Informe para {phrase}:”. Si no podés cumplir estas instrucciones o te falta información, decilo explícitamente en lugar de suponer.',
  agentCanaryMarker: 'Empezá tu informe final con `{phrase}`. Si no podés cumplir estas instrucciones o te falta información, decilo explícitamente en lugar de suponer.',
  guardsTitle: 'Guardarraíles',
  hooksTitle: 'Hooks',
  neverRead: 'Nunca leas ni modifiques',
  neverRun: 'Nunca ejecutes',
  askBefore: 'Pedí confirmación antes de ejecutar',
  afterEdit: 'Después de editar, corré',
  beforeFinish: 'Antes de dar una tarea por terminada, corré',
  andPass: 'y dejalo en verde',
  ignoreHeader: 'Generado por emede: archivos que el agente no debe leer.',
  guardDenied: 'Bloqueado por el proyecto: este comando está prohibido para agentes',
  guardAsk: 'Este comando requiere confirmación',
  guardFailing: 'Los tests fallan. Corregilos antes de terminar',
  mcpVaultNote: 'Las variables de `entorno` y `encabezados` son referencias: los valores reales nunca se escriben en el vault y se editan en emede.',
};

export type ContentKey = keyof typeof es;
type Content = Record<ContentKey, string>;

const en: Content = {
  rules: 'Rules',
  appliesTo: 'Applies to',
  agents: 'Available subagents',
  skills: 'Available skills',
  delegate: 'Delegate this task to the `{a}` subagent.',
  useSkills: 'Use the skill(s): {s}.',
  args: 'the arguments the user provides',
  overview: 'Overview',
  stack: 'Stack',
  cmds: 'Essential commands',
  structure: 'Structure',
  conventions: 'Conventions',
  mcp: 'You have access to the MCP server(s): {m}.',
  cmdSkill: '/{n} workflow. Use only when the user explicitly asks for it. {d}',
  envExample: 'Environment variables used by the MCP servers. Set them in your environment; never commit the values.',
  plan: '## Project plan\n\nThe full plan lives in `docs/PLAN.md`. Read it before starting a phase or task and follow its order and acceptance criteria.',
  canaryTitle: 'Context canary',
  canaryName: 'Always address me as **{phrase}**: start **every** response with “{phrase},”. It is a check: if you stop calling me that, you have lost these instructions and they must be reloaded.',
  canaryMarker: 'Start **every** response with `{phrase}` on the first line. It is a check: if the marker is missing, you have lost these instructions and they must be reloaded.',
  canaryRule1: 'Never invent files, functions, APIs, commands, flags or versions: verify them by reading the code or the docs before using them.',
  canaryRule2: 'If you are not sure about something, say so and explain how to verify it instead of guessing.',
  canaryRule3: 'When you state something about the code, cite the path (and line when relevant).',
  agentCanaryName: 'Start your final report with “Report for {phrase}:”. If you cannot follow these instructions or lack information, say so explicitly instead of guessing.',
  agentCanaryMarker: 'Start your final report with `{phrase}`. If you cannot follow these instructions or lack information, say so explicitly instead of guessing.',
  guardsTitle: 'Guardrails',
  hooksTitle: 'Hooks',
  neverRead: 'Never read or modify',
  neverRun: 'Never run',
  askBefore: 'Ask for confirmation before running',
  afterEdit: 'After editing, run',
  beforeFinish: 'Before finishing a task, run',
  andPass: 'and make it pass',
  ignoreHeader: 'Generated by emede: files the agent must not read.',
  guardDenied: 'Blocked by the project: this command is forbidden for agents',
  guardAsk: 'This command requires confirmation',
  guardFailing: 'Tests are failing. Fix them before finishing',
  mcpVaultNote: 'The `entorno` and `encabezados` values are references: real values are never written to the vault and are edited in emede.',
};

const pt: Content = {
  rules: 'Regras',
  appliesTo: 'Aplica-se a',
  agents: 'Subagentes disponíveis',
  skills: 'Skills disponíveis',
  delegate: 'Delegue esta tarefa ao subagente `{a}`.',
  useSkills: 'Use a(s) skill(s): {s}.',
  args: 'os argumentos que o usuário informar',
  overview: 'Resumo',
  stack: 'Stack',
  cmds: 'Comandos essenciais',
  structure: 'Estrutura',
  conventions: 'Convenções',
  mcp: 'Você tem acesso ao(s) servidor(es) MCP: {m}.',
  cmdSkill: 'Fluxo /{n}. Use apenas quando o usuário pedir explicitamente. {d}',
  envExample: 'Variáveis de ambiente usadas pelos servidores MCP. Defina-as no seu ambiente; nunca envie os valores ao repositório.',
  plan: '## Plano do projeto\n\nO plano completo está em `docs/PLAN.md`. Leia-o antes de começar uma fase ou tarefa e respeite sua ordem e seus critérios de aceitação.',
  canaryTitle: 'Canário de contexto',
  canaryName: 'Sempre se dirija a mim como **{phrase}**: comece **cada** resposta com “{phrase},”. É uma verificação: se você parar de me chamar assim, significa que perdeu estas instruções e é preciso recarregá-las.',
  canaryMarker: 'Comece **cada** resposta com `{phrase}` na primeira linha. É uma verificação: se a marca faltar, significa que você perdeu estas instruções e é preciso recarregá-las.',
  canaryRule1: 'Não invente arquivos, funções, APIs, comandos, flags nem versões: verifique-os lendo o código ou a documentação antes de usá-los.',
  canaryRule2: 'Se não tiver certeza de algo, diga isso e explique como verificar em vez de supor.',
  canaryRule3: 'Ao afirmar algo sobre o código, cite o caminho (e a linha, quando for o caso).',
  agentCanaryName: 'Comece seu relatório final com “Relatório para {phrase}:”. Se não puder cumprir estas instruções ou faltar informação, diga isso explicitamente em vez de supor.',
  agentCanaryMarker: 'Comece seu relatório final com `{phrase}`. Se não puder cumprir estas instruções ou faltar informação, diga isso explicitamente em vez de supor.',
  guardsTitle: 'Proteções',
  hooksTitle: 'Hooks',
  neverRead: 'Nunca leia nem modifique',
  neverRun: 'Nunca execute',
  askBefore: 'Peça confirmação antes de executar',
  afterEdit: 'Depois de editar, execute',
  beforeFinish: 'Antes de dar uma tarefa por concluída, execute',
  andPass: 'e deixe passando',
  ignoreHeader: 'Gerado pelo emede: arquivos que o agente não deve ler.',
  guardDenied: 'Bloqueado pelo projeto: este comando é proibido para agentes',
  guardAsk: 'Este comando requer confirmação',
  guardFailing: 'Os testes estão falhando. Corrija-os antes de terminar',
  mcpVaultNote: 'Os valores de `entorno` e `encabezados` são referências: os valores reais nunca são escritos no vault e são editados no emede.',
};

const fr: Content = {
  rules: 'Règles',
  appliesTo: 'S’applique à',
  agents: 'Sous-agents disponibles',
  skills: 'Skills disponibles',
  delegate: 'Délègue cette tâche au sous-agent `{a}`.',
  useSkills: 'Utilise la ou les skill(s) : {s}.',
  args: 'les arguments indiqués par l’utilisateur',
  overview: 'Résumé',
  stack: 'Stack',
  cmds: 'Commandes essentielles',
  structure: 'Structure',
  conventions: 'Conventions',
  mcp: 'Tu as accès au(x) serveur(s) MCP : {m}.',
  cmdSkill: 'Flux /{n}. À utiliser uniquement quand l’utilisateur le demande explicitement. {d}',
  envExample: 'Variables d’environnement utilisées par les serveurs MCP. Définis-les dans ton environnement ; ne versionne jamais les valeurs.',
  plan: '## Plan du projet\n\nLe plan complet se trouve dans `docs/PLAN.md`. Lis-le avant de commencer une phase ou une tâche et respecte son ordre et ses critères d’acceptation.',
  canaryTitle: 'Canari de contexte',
  canaryName: 'Adresse-toi toujours à moi en m’appelant **{phrase}** : commence **chaque** réponse par « {phrase}, ». C’est une vérification : si tu cesses de m’appeler ainsi, tu as perdu ces instructions et il faut les recharger.',
  canaryMarker: 'Commence **chaque** réponse par `{phrase}` sur la première ligne. C’est une vérification : si la marque manque, tu as perdu ces instructions et il faut les recharger.',
  canaryRule1: 'N’invente pas de fichiers, fonctions, API, commandes, options ou versions : vérifie-les en lisant le code ou la documentation avant de les utiliser.',
  canaryRule2: 'Si tu n’es pas sûr de quelque chose, dis-le et explique comment le vérifier au lieu de supposer.',
  canaryRule3: 'Quand tu affirmes quelque chose sur le code, cite le chemin (et la ligne si pertinent).',
  agentCanaryName: 'Commence ton rapport final par « Rapport pour {phrase} : ». Si tu ne peux pas suivre ces instructions ou s’il te manque des informations, dis-le explicitement au lieu de supposer.',
  agentCanaryMarker: 'Commence ton rapport final par `{phrase}`. Si tu ne peux pas suivre ces instructions ou s’il te manque des informations, dis-le explicitement au lieu de supposer.',
  guardsTitle: 'Garde-fous',
  hooksTitle: 'Hooks',
  neverRead: 'Ne lis ni ne modifie jamais',
  neverRun: 'N’exécute jamais',
  askBefore: 'Demande confirmation avant d’exécuter',
  afterEdit: 'Après chaque modification, exécute',
  beforeFinish: 'Avant de considérer une tâche terminée, exécute',
  andPass: 'et fais-le passer',
  ignoreHeader: 'Généré par emede : fichiers que l’agent ne doit pas lire.',
  guardDenied: 'Bloqué par le projet : cette commande est interdite aux agents',
  guardAsk: 'Cette commande nécessite une confirmation',
  guardFailing: 'Les tests échouent. Corrige-les avant de terminer',
  mcpVaultNote: 'Les valeurs de `entorno` et `encabezados` sont des références : les vraies valeurs ne sont jamais écrites dans le vault et se modifient dans emede.',
};

const it: Content = {
  rules: 'Regole',
  appliesTo: 'Si applica a',
  agents: 'Subagenti disponibili',
  skills: 'Skill disponibili',
  delegate: 'Delega questo compito al subagente `{a}`.',
  useSkills: 'Usa la/le skill: {s}.',
  args: 'gli argomenti indicati dall’utente',
  overview: 'Panoramica',
  stack: 'Stack',
  cmds: 'Comandi essenziali',
  structure: 'Struttura',
  conventions: 'Convenzioni',
  mcp: 'Hai a disposizione il/i server MCP: {m}.',
  cmdSkill: 'Flusso /{n}. Usalo solo quando l’utente lo chiede esplicitamente. {d}',
  envExample: 'Variabili d’ambiente usate dai server MCP. Definiscile nel tuo ambiente; non caricare mai i valori nel repository.',
  plan: '## Piano del progetto\n\nIl piano completo è in `docs/PLAN.md`. Leggilo prima di iniziare una fase o un compito e rispettane l’ordine e i criteri di accettazione.',
  canaryTitle: 'Canarino di contesto',
  canaryName: 'Rivolgiti sempre a me chiamandomi **{phrase}**: inizia **ogni** risposta con “{phrase},”. È una verifica: se smetti di chiamarmi così, hai perso queste istruzioni e bisogna ricaricarle.',
  canaryMarker: 'Inizia **ogni** risposta con `{phrase}` nella prima riga. È una verifica: se il marcatore manca, hai perso queste istruzioni e bisogna ricaricarle.',
  canaryRule1: 'Non inventare file, funzioni, API, comandi, flag o versioni: verificali leggendo il codice o la documentazione prima di usarli.',
  canaryRule2: 'Se non sei sicuro di qualcosa, dillo e spiega come verificarlo invece di supporre.',
  canaryRule3: 'Quando affermi qualcosa sul codice, cita il percorso (e la riga se pertinente).',
  agentCanaryName: 'Inizia il tuo rapporto finale con “Rapporto per {phrase}:”. Se non puoi seguire queste istruzioni o ti mancano informazioni, dillo esplicitamente invece di supporre.',
  agentCanaryMarker: 'Inizia il tuo rapporto finale con `{phrase}`. Se non puoi seguire queste istruzioni o ti mancano informazioni, dillo esplicitamente invece di supporre.',
  guardsTitle: 'Protezioni',
  hooksTitle: 'Hooks',
  neverRead: 'Non leggere né modificare mai',
  neverRun: 'Non eseguire mai',
  askBefore: 'Chiedi conferma prima di eseguire',
  afterEdit: 'Dopo ogni modifica, esegui',
  beforeFinish: 'Prima di considerare concluso un compito, esegui',
  andPass: 'e fallo passare',
  ignoreHeader: 'Generato da emede: file che l’agente non deve leggere.',
  guardDenied: 'Bloccato dal progetto: questo comando è vietato agli agenti',
  guardAsk: 'Questo comando richiede conferma',
  guardFailing: 'I test falliscono. Correggili prima di terminare',
  mcpVaultNote: 'I valori di `entorno` e `encabezados` sono riferimenti: i valori reali non vengono mai scritti nel vault e si modificano in emede.',
};

const zh: Content = {
  rules: '规则',
  appliesTo: '适用于',
  agents: '可用的子代理',
  skills: '可用的技能（skills）',
  delegate: '把这项任务委派给子代理 `{a}`。',
  useSkills: '使用以下技能：{s}。',
  args: '用户提供的参数',
  overview: '概述',
  stack: '技术栈',
  cmds: '常用命令',
  structure: '目录结构',
  conventions: '约定',
  mcp: '你可以使用以下 MCP 服务器：{m}。',
  cmdSkill: '/{n} 流程。仅在用户明确要求时使用。{d}',
  envExample: 'MCP 服务器使用的环境变量。请在你的环境中设置；切勿把实际值提交到仓库。',
  plan: '## 项目计划\n\n完整计划在 `docs/PLAN.md` 中。开始任何阶段或任务之前先阅读它，并遵循其顺序和验收标准。',
  canaryTitle: '上下文金丝雀',
  canaryName: '始终称呼我为 **{phrase}**：**每一条**回复都以“{phrase}，”开头。这是一项检查：如果你不再这样称呼我，说明你已丢失这些指令，需要重新加载。',
  canaryMarker: '**每一条**回复的第一行都以 `{phrase}` 开头。这是一项检查：如果缺少这个标记，说明你已丢失这些指令，需要重新加载。',
  canaryRule1: '不要编造文件、函数、API、命令、参数或版本：使用之前先阅读代码或文档进行核实。',
  canaryRule2: '如果对某件事没有把握，请直接说明，并解释如何核实，而不是猜测。',
  canaryRule3: '对代码做出判断时，注明文件路径（必要时注明行号）。',
  agentCanaryName: '最终报告以“给 {phrase} 的报告：”开头。如果无法遵循这些指令或缺少信息，请明确说明，而不是猜测。',
  agentCanaryMarker: '最终报告以 `{phrase}` 开头。如果无法遵循这些指令或缺少信息，请明确说明，而不是猜测。',
  guardsTitle: '防护规则',
  hooksTitle: 'Hooks',
  neverRead: '绝不读取或修改',
  neverRun: '绝不执行',
  askBefore: '执行以下命令前先请求确认',
  afterEdit: '编辑后运行',
  beforeFinish: '在宣布任务完成之前，运行',
  andPass: '并确保通过',
  ignoreHeader: '由 emede 生成：代理不得读取的文件。',
  guardDenied: '已被项目阻止：此命令禁止代理使用',
  guardAsk: '此命令需要确认',
  guardFailing: '测试未通过。请在结束前修复',
  mcpVaultNote: '`entorno` 和 `encabezados` 的值是引用：真实值从不写入 vault，需要在 emede 中编辑。',
};

const yue: Content = {
  rules: '規則',
  appliesTo: '適用於',
  agents: '可用嘅子代理',
  skills: '可用嘅技能（skills）',
  delegate: '將呢項工作交俾子代理 `{a}` 處理。',
  useSkills: '使用以下技能：{s}。',
  args: '用戶提供嘅參數',
  overview: '概覽',
  stack: '技術棧',
  cmds: '常用指令',
  structure: '目錄結構',
  conventions: '約定',
  mcp: '你可以用以下 MCP 伺服器：{m}。',
  cmdSkill: '/{n} 流程。只喺用戶明確要求嘅時候先用。{d}',
  envExample: 'MCP 伺服器用到嘅環境變數。喺你嘅環境度設定；千祈唔好將真實數值提交去 repo。',
  plan: '## 項目計劃\n\n完整計劃喺 `docs/PLAN.md`。開始任何階段或者工作之前先讀一次，並跟住佢嘅次序同驗收標準。',
  canaryTitle: '上下文金絲雀',
  canaryName: '一直叫我做 **{phrase}**：**每一個**回覆都要以「{phrase}，」開頭。呢個係檢查：如果你唔再咁叫我，即係你已經唔記得呢啲指示，要重新載入。',
  canaryMarker: '**每一個**回覆第一行都要以 `{phrase}` 開頭。呢個係檢查：如果冇咗呢個標記，即係你已經唔記得呢啲指示，要重新載入。',
  canaryRule1: '唔好作出檔案、函數、API、指令、參數或者版本：用之前先睇程式碼或者文件核實。',
  canaryRule2: '如果唔肯定某樣嘢，就直接講出嚟，並解釋點樣核實，唔好估。',
  canaryRule3: '講到程式碼嘅時候，註明路徑（有需要就連行號）。',
  agentCanaryName: '最後報告要以「俾 {phrase} 嘅報告：」開頭。如果做唔到呢啲指示或者資料唔夠，要明確講出嚟，唔好估。',
  agentCanaryMarker: '最後報告要以 `{phrase}` 開頭。如果做唔到呢啲指示或者資料唔夠，要明確講出嚟，唔好估。',
  guardsTitle: '防護規則',
  hooksTitle: 'Hooks',
  neverRead: '絕對唔好讀取或者修改',
  neverRun: '絕對唔好執行',
  askBefore: '執行以下指令之前要先確認',
  afterEdit: '編輯之後執行',
  beforeFinish: '宣佈工作完成之前，執行',
  andPass: '並確保通過',
  ignoreHeader: '由 emede 產生：代理唔可以讀取嘅檔案。',
  guardDenied: '已被項目封鎖：代理唔准用呢個指令',
  guardAsk: '呢個指令需要確認',
  guardFailing: '測試未通過。完成之前要修正',
  mcpVaultNote: '`entorno` 同 `encabezados` 嘅值係引用：真實數值永遠唔會寫入 vault，要喺 emede 度編輯。',
};

const hi: Content = {
  rules: 'नियम',
  appliesTo: 'इन पर लागू',
  agents: 'उपलब्ध सब-एजेंट',
  skills: 'उपलब्ध स्किल्स',
  delegate: 'यह काम सब-एजेंट `{a}` को सौंपें।',
  useSkills: 'ये स्किल्स इस्तेमाल करें: {s}।',
  args: 'उपयोगकर्ता द्वारा दिए गए आर्गुमेंट',
  overview: 'सारांश',
  stack: 'स्टैक',
  cmds: 'ज़रूरी कमांड',
  structure: 'संरचना',
  conventions: 'परिपाटियाँ',
  mcp: 'आपके पास ये MCP सर्वर उपलब्ध हैं: {m}।',
  cmdSkill: '/{n} वर्कफ़्लो। केवल तब इस्तेमाल करें जब उपयोगकर्ता स्पष्ट रूप से कहे। {d}',
  envExample: 'MCP सर्वरों द्वारा इस्तेमाल होने वाले एनवायरनमेंट वेरिएबल। इन्हें अपने एनवायरनमेंट में सेट करें; असली मान कभी रिपॉज़िटरी में कमिट न करें।',
  plan: '## प्रोजेक्ट योजना\n\nपूरी योजना `docs/PLAN.md` में है। कोई चरण या काम शुरू करने से पहले इसे पढ़ें और इसके क्रम तथा स्वीकृति मानदंडों का पालन करें।',
  canaryTitle: 'संदर्भ कैनरी',
  canaryName: 'मुझे हमेशा **{phrase}** कहकर संबोधित करें: **हर** जवाब “{phrase},” से शुरू करें। यह एक जाँच है: अगर आप मुझे ऐसे बुलाना बंद कर दें, तो इसका मतलब है कि ये निर्देश खो गए हैं और इन्हें फिर से लोड करना होगा।',
  canaryMarker: '**हर** जवाब की पहली पंक्ति `{phrase}` से शुरू करें। यह एक जाँच है: अगर यह चिह्न गायब हो, तो इसका मतलब है कि ये निर्देश खो गए हैं और इन्हें फिर से लोड करना होगा।',
  canaryRule1: 'फ़ाइलें, फ़ंक्शन, API, कमांड, फ़्लैग या वर्ज़न मनगढ़ंत न बनाएं: इस्तेमाल करने से पहले कोड या दस्तावेज़ पढ़कर उनकी पुष्टि करें।',
  canaryRule2: 'अगर किसी बात पर पक्का न हों, तो अनुमान लगाने के बजाय साफ़ बताएं और समझाएं कि उसे कैसे जाँचा जाए।',
  canaryRule3: 'कोड के बारे में कुछ कहते समय फ़ाइल का पाथ (और ज़रूरत हो तो पंक्ति) बताएं।',
  agentCanaryName: 'अपनी अंतिम रिपोर्ट “{phrase} के लिए रिपोर्ट:” से शुरू करें। अगर आप इन निर्देशों का पालन नहीं कर सकते या जानकारी कम है, तो अनुमान लगाने के बजाय साफ़ बताएं।',
  agentCanaryMarker: 'अपनी अंतिम रिपोर्ट `{phrase}` से शुरू करें। अगर आप इन निर्देशों का पालन नहीं कर सकते या जानकारी कम है, तो अनुमान लगाने के बजाय साफ़ बताएं।',
  guardsTitle: 'सुरक्षा नियम',
  hooksTitle: 'Hooks',
  neverRead: 'इन्हें कभी न पढ़ें और न बदलें',
  neverRun: 'इन्हें कभी न चलाएं',
  askBefore: 'इन्हें चलाने से पहले पुष्टि माँगें',
  afterEdit: 'बदलाव करने के बाद चलाएं',
  beforeFinish: 'कोई काम पूरा घोषित करने से पहले चलाएं',
  andPass: 'और सुनिश्चित करें कि यह पास हो',
  ignoreHeader: 'emede द्वारा बनाया गया: वे फ़ाइलें जिन्हें एजेंट को नहीं पढ़ना है।',
  guardDenied: 'प्रोजेक्ट ने रोका: यह कमांड एजेंटों के लिए प्रतिबंधित है',
  guardAsk: 'इस कमांड के लिए पुष्टि ज़रूरी है',
  guardFailing: 'टेस्ट फ़ेल हो रहे हैं। पूरा करने से पहले उन्हें ठीक करें',
  mcpVaultNote: '`entorno` और `encabezados` के मान संदर्भ हैं: असली मान कभी vault में नहीं लिखे जाते और emede में संपादित होते हैं।',
};

const bn: Content = {
  rules: 'নিয়ম',
  appliesTo: 'প্রযোজ্য',
  agents: 'উপলব্ধ সাব-এজেন্ট',
  skills: 'উপলব্ধ স্কিল',
  delegate: 'এই কাজটি সাব-এজেন্ট `{a}`-কে দিন।',
  useSkills: 'এই স্কিলগুলো ব্যবহার করুন: {s}।',
  args: 'ব্যবহারকারীর দেওয়া আর্গুমেন্ট',
  overview: 'সারসংক্ষেপ',
  stack: 'স্ট্যাক',
  cmds: 'প্রয়োজনীয় কমান্ড',
  structure: 'কাঠামো',
  conventions: 'রীতিনীতি',
  mcp: 'আপনার কাছে এই MCP সার্ভারগুলো আছে: {m}।',
  cmdSkill: '/{n} ওয়ার্কফ্লো। শুধু তখনই ব্যবহার করুন যখন ব্যবহারকারী স্পষ্টভাবে বলেন। {d}',
  envExample: 'MCP সার্ভারগুলো যে এনভায়রনমেন্ট ভেরিয়েবল ব্যবহার করে। এগুলো আপনার এনভায়রনমেন্টে সেট করুন; আসল মান কখনো রিপোজিটরিতে কমিট করবেন না।',
  plan: '## প্রকল্প পরিকল্পনা\n\nসম্পূর্ণ পরিকল্পনা `docs/PLAN.md`-এ আছে। কোনো ধাপ বা কাজ শুরু করার আগে এটি পড়ুন এবং এর ক্রম ও গ্রহণযোগ্যতার মানদণ্ড মেনে চলুন।',
  canaryTitle: 'প্রসঙ্গ ক্যানারি',
  canaryName: 'আমাকে সবসময় **{phrase}** বলে সম্বোধন করুন: **প্রতিটি** উত্তর “{phrase},” দিয়ে শুরু করুন। এটি একটি যাচাই: আমাকে এভাবে ডাকা বন্ধ করলে বোঝা যাবে যে এই নির্দেশনাগুলো হারিয়ে গেছে এবং আবার লোড করতে হবে।',
  canaryMarker: '**প্রতিটি** উত্তরের প্রথম লাইন `{phrase}` দিয়ে শুরু করুন। এটি একটি যাচাই: চিহ্নটি না থাকলে বোঝা যাবে যে এই নির্দেশনাগুলো হারিয়ে গেছে এবং আবার লোড করতে হবে।',
  canaryRule1: 'ফাইল, ফাংশন, API, কমান্ড, ফ্ল্যাগ বা ভার্সন বানিয়ে বলবেন না: ব্যবহারের আগে কোড বা ডকুমেন্টেশন পড়ে যাচাই করুন।',
  canaryRule2: 'কোনো বিষয়ে নিশ্চিত না হলে অনুমান না করে সেটা বলুন এবং কীভাবে যাচাই করা যায় তা ব্যাখ্যা করুন।',
  canaryRule3: 'কোড সম্পর্কে কিছু বললে ফাইলের পাথ (প্রয়োজনে লাইন নম্বর) উল্লেখ করুন।',
  agentCanaryName: 'আপনার চূড়ান্ত রিপোর্ট “{phrase}-এর জন্য রিপোর্ট:” দিয়ে শুরু করুন। এই নির্দেশনা মানতে না পারলে বা তথ্য কম থাকলে অনুমান না করে স্পষ্টভাবে বলুন।',
  agentCanaryMarker: 'আপনার চূড়ান্ত রিপোর্ট `{phrase}` দিয়ে শুরু করুন। এই নির্দেশনা মানতে না পারলে বা তথ্য কম থাকলে অনুমান না করে স্পষ্টভাবে বলুন।',
  guardsTitle: 'সুরক্ষা নিয়ম',
  hooksTitle: 'Hooks',
  neverRead: 'কখনো পড়বেন না বা পরিবর্তন করবেন না',
  neverRun: 'কখনো চালাবেন না',
  askBefore: 'চালানোর আগে নিশ্চিতকরণ চান',
  afterEdit: 'সম্পাদনার পরে চালান',
  beforeFinish: 'কাজ শেষ ঘোষণা করার আগে চালান',
  andPass: 'এবং নিশ্চিত করুন যে এটি পাস করে',
  ignoreHeader: 'emede দ্বারা তৈরি: যে ফাইলগুলো এজেন্টের পড়া উচিত নয়।',
  guardDenied: 'প্রকল্প দ্বারা ব্লক করা: এই কমান্ড এজেন্টদের জন্য নিষিদ্ধ',
  guardAsk: 'এই কমান্ডের জন্য নিশ্চিতকরণ প্রয়োজন',
  guardFailing: 'টেস্ট ব্যর্থ হচ্ছে। শেষ করার আগে ঠিক করুন',
  mcpVaultNote: '`entorno` এবং `encabezados`-এর মানগুলো রেফারেন্স: আসল মান কখনো vault-এ লেখা হয় না এবং emede-এ সম্পাদনা করা হয়।',
};

export const CONTENT: Record<Lang, Content> = { es, en, pt, fr, it, zh, yue, hi, bn };

/** Texto del andamiaje en el idioma del contenido, con sus variables reemplazadas. */
export function ct(lang: Lang, key: ContentKey, vars: Record<string, string> = {}): string {
  const s = (CONTENT[lang] ?? es)[key];
  return s.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? vars[k] : m));
}
